/** Karakter ≠ makara sembolü. Sembol temayı öder; figür konuyu bedenle anlatır. */
export const FIGURES = {
  sweet: {
    body: "peri",
    mark: "lolipop",
    story: "Şeker yağmurunda tacir peri; çarpan dilde erir.",
    idle: "kalça salınımı",
    roar: "dudak ısırır, şeker kırılır",
    win: "baş geri, yağmur",
    miss: "lolipop düşer",
  },
  olympus: {
    body: "tanrıça",
    mark: "yıldırım diadem",
    story: "Kapıyı ten ve volt açar; roar gök yarığı.",
    idle: "omuz arkası bakış",
    roar: "kol kalkar, çarpış",
    win: "pelerin açılır",
    miss: "volt söner",
  },
  nova: {
    body: "yıldız muhafız",
    mark: "kesme elmas",
    story: "Nebula teninde kristal damar; X kristali büyütür.",
    idle: "yavaş yörünge",
    roar: "göz mercek",
    win: "elmas patlar",
    miss: "ışık solar",
  },
  reef: {
    body: "avcı",
    mark: "yüzgeç bıçak",
    story: "Resif kralı; roar suyu yarar.",
    idle: "yana kayış",
    roar: "çene açılır",
    win: "su fışkırır",
    miss: "yüzgeç iner",
  },
  rich: {
    body: "avcı kadın",
    mark: "açık harita",
    story: "Hazine ten ve mürekkep; roar mühür kırılır.",
    idle: "kitap okşar",
    roar: "harita açılır",
    win: "altın dökülür",
    miss: "sayfa kapanır",
  },
  west: {
    body: "şerif",
    mark: "namlu",
    story: "Kasaba kanunu; roar tetik.",
    idle: "şapka eğimi",
    roar: "çekiş",
    win: "duman",
    miss: "toz",
  },
  mystic: {
    body: "falcı",
    mark: "küre",
    story: "Kehanet teninden okunur; roar küre çatlar.",
    idle: "eller kürede",
    roar: "göz beyazlar",
    win: "sis dağılır",
    miss: "küre kararır",
  },
  wolf: {
    body: "sürü reisi",
    mark: "diş",
    story: "Gece teni; roar uluma.",
    idle: "pace",
    roar: "baş geri ulur",
    win: "ay parlar",
    miss: "kulak düşer",
  },
  flame: {
    body: "köz prenses",
    mark: "alev saç",
    story: "Dans eden ateş; roar alev boyu.",
    idle: "titreşim",
    roar: "saç alev",
    win: "kıvılcım",
    miss: "köz söner",
  },
  forest: {
    body: "koruyucu",
    mark: "yaprak taç",
    story: "Tapınak bedeni kök; roar dal açılır.",
    idle: "nefes ağaç",
    roar: "omuz yeşerir",
    win: "yaprak yağar",
    miss: "dal kırılır",
  },
  pharaoh: {
    body: "güneş muhafız",
    mark: "uraeus",
    story: "Mezar altını ten; roar güneş disk.",
    idle: "profil bekçi",
    roar: "disk yükselir",
    win: "kum uçuşur",
    miss: "disk iner",
  },
  pirate: {
    body: "kaptan",
    mark: "çıpa küpe",
    story: "Fırtına bedeni; roar dalga.",
    idle: "güverte salınım",
    roar: "kılıç çizgisi",
    win: "sprey",
    miss: "yelken düşer",
  },
  neon: {
    body: "sokak ışığı",
    mark: "neon kalp",
    story: "Gece cildi fosfor; roar scanline.",
    idle: "pulse",
    roar: "göz neon",
    win: "scan",
    miss: "kesik elektrik",
  },
  samurai: {
    body: "son kılıç",
    mark: "saya",
    story: "Bahçe disiplini; roar kesik.",
    idle: "still",
    roar: "kılıç yarım çekilir",
    win: "çiçek kesik",
    miss: "saya kapanır",
  },
  ice: {
    body: "ayaz hanım",
    mark: "buz taç",
    story: "Kale soğuğu ten; roar kırılma.",
    idle: "drift",
    roar: "nefes buhar",
    win: "kırık cam",
    miss: "buhar kesilir",
  },
  dragon: {
    body: "ocak bekçi",
    mark: "pul omuz",
    story: "Ejder omuzda yaşar; roar ateş nefesi.",
    idle: "kanat gölge",
    roar: "çene ateş",
    win: "kanat açılır",
    miss: "köz düşer",
  },
  circus: {
    body: "sahne ustası",
    mark: "maske",
    story: "Karnaval bedeni gösteri; roar maske düşer.",
    idle: "bounce",
    roar: "yay gerilir",
    win: "konfeti",
    miss: "maske kayar",
  },
  vault: {
    body: "kasa bekçi",
    mark: "kilit kalça zincir",
    story: "Altın ten kilit; roar mandal.",
    idle: "tick",
    roar: "kasa açılır",
    win: "külçe",
    miss: "kilit şak",
  },
};

export function figureOf(game) {
  if (!game) return null;
  return FIGURES[game.id] || {
    body: game.character,
    mark: game.emoji,
    story: game.theme,
    idle: game.motion,
    roar: "c",
    win: "win",
    miss: "miss",
  };
}
